# Generated by Django 3.2.19 on 2023-06-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
